/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package talham7391.matchmaker

import java.util.*
import kotlin.test.Test
import kotlin.test.assertEquals

interface AgentListener {
    fun agentReady(agent: MyAgent)
}

data class MyAgent(val name: String, val listener: AgentListener) : Agent {
    var lobby: MyLobby? = null

    override fun joinedLobby(lobby: Lobby) {
        this.lobby = lobby as? MyLobby
        listener.agentReady(this)
    }
}

data class MyLobbyProperties(
        val map: String
) : LobbyProperties

data class MyLobby(
        val properties: MyLobbyProperties,
        val maxNumPlayers: Int
) : Lobby {
    val agents = mutableListOf<Agent>()
}

class MyMatchMakerConfig(val lobbySize: Int) : MatchMakerConfig {
    override fun makeLobby(lobbyProperties: LobbyProperties): Lobby {
        return MyLobby(lobbyProperties as MyLobbyProperties, lobbySize)
    }

    override fun addAgentToLobby(agent: Agent, lobby: Lobby): Boolean {
        val l = lobby as? MyLobby
        l?.let {
            it.agents.add(agent)
            return true
        }
        return false
    }

    override fun isLobbyReady(lobby: Lobby): Boolean {
        val p = lobby as MyLobby
        return p.agents.size == p.maxNumPlayers
    }
}

class TestCanMakeMatch : AgentListener {
    var readyAgent: MyAgent? = null

    @Test fun testCanMakeMatch() {
        val mm = MatchMaker(MyMatchMakerConfig(1))
        val map = "HALO"
        mm.registerAgent(MyAgent("bob", this), MyLobbyProperties(map))
        assert(readyAgent != null)
        assert(readyAgent?.lobby?.properties?.map == map)
        assert(readyAgent?.let { it.lobby?.agents?.contains(it) } ?: false)
    }

    override fun agentReady(agent: MyAgent) {
        readyAgent = agent
    }
}

class TestCanJoinMultipleMatches : AgentListener {
    val lobbies = mutableSetOf<MyLobby>()

    @Test fun testCanJoinMultipleMatches() {
        val lobbySize = 8
        val numLobbies = 10
        val mm = MatchMaker(MyMatchMakerConfig(lobbySize))
        repeat(numLobbies) {
            val m = "HALO - ${Random().nextInt()}"
            repeat(lobbySize) {
                mm.registerAgent(MyAgent("bob", this), MyLobbyProperties(m))
            }
        }
        assertEquals(numLobbies, lobbies.size)
    }

    override fun agentReady(agent: MyAgent) {
        agent.lobby?.let { lobbies.add(it) }
    }
}

class TestPlayersJoinRightMatch : AgentListener {

    @Test fun testPlayersJoinRightMatch() {
        val mm = MatchMaker(MyMatchMakerConfig(2))

        val p1 = MyAgent("p1", this)
        val p2 = MyAgent("p2", this)
        val p3 = MyAgent("p3", this)
        val p4 = MyAgent("p4", this)

        mm.registerAgent(p1, MyLobbyProperties("president"))
        mm.registerAgent(p2, MyLobbyProperties("estimation"))
        mm.registerAgent(p3, MyLobbyProperties("estimation"))
        mm.registerAgent(p4, MyLobbyProperties("president"))
    }

    override fun agentReady(agent: MyAgent) {
        if (agent.name == "p1" || agent.name == "p4") {
            assertEquals("president", agent.lobby?.properties?.map)
        } else {
            assertEquals("estimation", agent.lobby?.properties?.map)
        }
    }
}
